export const categoryOptions = [
    { text: 'Камини', value: 'Камини', key: 'Fireplaces' },
    { text: 'Готварски печки', value: 'Готварски печки', key: 'Cooking stoves' },
    { text: 'Консумативи', value: 'Консумативи', key: 'Consumables' },
    { text: 'Други/Аксесоари', value: 'Други/Аксесоари', key: 'Other/Accessories' },
    // { text: 'Плодове', value: 'Плодове', key: 'Fruits' },
    // { text: 'Млечни продукти', value: 'Млечни продукти', key: 'Dairy products' },
    // { text: 'Хлебни изделия', value: 'Хлебни изделия', key: 'Bakery products' },
    // { text: 'Напитки', value: 'Напитки', key: 'Drinks' },
    // { text: 'Сладкиши', value: 'Сладкиши' },
    // { text: 'Замразени храни', value: 'Замразени храни', key: 'Frozen foods' },
    // { text: 'Консерви', value: 'Консерви', key: 'Canned' },
    // { text: 'Домакински', value: 'Домакински', key: 'Household' },
    // { text: 'Козметика', value: 'Козметика', key: 'Cosmetics' },
    // { text: 'Хигиена', value: 'Хигиена', key: 'Hygiene' },
    // { text: 'Детски', value: 'Детски', key: 'Children' },
    // { text: 'Алкохолни напитки', value: 'Алкохолни напитки', key: 'Alcoholic drinks' },
    // { text: 'Кафе', value: 'Кафе', key: 'Coffee' },
    // { text: 'Чай', value: 'Чай', key: 'Tea' },
    // { text: 'Подправки', value: 'Подправки', key: 'Spices' },
    // { text: 'Специални', value: 'Специални', key: 'Special' },
    // { text: 'Био', value: 'Био', key: 'Bio' },
    // { text: 'Сезонни', value: 'Сезонни', key: 'Seasonal' },
    // { text: 'Сурови', value: 'Сурови', key: 'Raw' },
    // { text: 'Веган', value: 'Веган', key: 'Vegan' },
    // { text: 'Вегетариански', value: 'Вегетариански', key: 'Vegetarian' },
    // { text: 'Без глутен', value: 'Без глутен', key: 'Gluten free' },
    // { text: 'Без лактоза', value: 'Без лактоза', key: 'Lactose free' },
    // { text: 'Без захар', value: 'Без захар', key: 'Sugar free' },
    // { text: 'Без консерванти', value: 'Без консерванти', key: 'Preservative free' },
    // { text: 'Без ГМО', value: 'Без ГМО', key: 'GMO free' },
    // { text: 'Без палмово масло', value: 'Без палмово масло', key: 'Palm oil free' },
    // { text: 'Без изкуствени оцветители', value: 'Без изкуствени оцветители', key: 'No artificial colors' },
    // { text: 'Без изкуствени аромати', value: 'Без изкуствени аромати', key: 'No artificial flavors' },
    // { text: 'Без изкуствени подсладители', value: 'Без изкуствени подсладители', key: 'No artificial sweeteners' },
    // { text: 'Без изкуствени подобрители', value: 'Без изкуствени подобрители', key: 'No artificial enhancers' },
    // { text: 'Без изкуствени подправки', value: 'Без изкуствени подправки', key: 'No artificial spices' },
    // { text: 'Без изкуствени добавки', value: 'Без изкуствени добавки', key: 'No artificial additives' },
    // { text: 'Без изкуствени консерванти', value: 'Без изкуствени консерванти', key: 'No artificial preservatives' },
    // { text: 'Без изкуствени овкусители', value: 'Без изкуствени овкусители', key: 'No artificial flavorings' },
];